### ISSUE TITLE
ImportError (circular import)

### ISSUE THREAD

**Issue by digitalblossom** [deta/deta-python#42]
When running the sample code from the website...
```
from deta import Deta

# initialize with a project key
deta = Deta("{key}")

# create and use as many Drives as you want!
photos = deta.Drive("Test")
photos.put("car.jpg", path="./test/car.jpg")
```
... i get the following error:
```
ImportError: cannot import name 'Deta' from partially initialized module 'deta' (most likely due to a circular import) (C:\Users\user\Documents\...\...\...\...\deta.py)
```
Edit: This is the case with the package versions 1.0.0rc0, 0.9 and 0.8

**Comment by aavshr** [comment]
hi @digitalblossom , you should not name your file `deta.py` as the module name itself is `deta`.

**Comment by digitalblossom** [comment]
> hi @digitalblossom , you should not name your file `deta.py` as the module name itself is `deta`.

Thanks for your help :)
