### ISSUE TITLE
Redundant send_email

### ISSUE THREAD

**Issue by leits** [deta/deta-python#45]
Hi, Deta team!
Looks like I found the code for your internal needs in the client 😅

https://github.com/deta/deta-python/blob/5d0e5ef6b2ffa319403e55dfcb46ca5daf7410d0/deta/__init__.py#L62-L85

**Comment by xeust** [comment]
Hi there @leits,

This code is actually for our upcoming email service 🤫

**Comment by leits** [comment]
Spoiler 😄
