### ISSUE TITLE
Use explicit exception raising instead of asserts

### ISSUE THREAD

**Issue by leits** [deta/deta-python#46]
> The current code generator emits no code for an assert statement when optimization is requested at compile time.

https://docs.python.org/3/reference/simple_stmts.html#the-assert-statement
and https://stackoverflow.com/questions/944592/best-practice-for-using-assert

Please, don't use asserts outside of tests 😃

**Comment by leits** [comment]
Use explicit exception raising instead of asserts #46

**Comment by leits** [comment]
Found good examples in the repository:
https://github.com/deta/deta-python/blob/master/deta/base.py#L84-L86

**Comment by abdelhai** [comment]
Thanks @leits for the feedback! We will consider it in our next release. I think in general, we need to raise better errors.

**Comment by abdelhai** [comment]
thanks Andrii! should be resolved by #69
