### ISSUE TITLE
How to run tests localy?

### ISSUE THREAD

**Issue by leits** [deta/deta-python#47]
I found at least 3 variables that try to get out of the environment in the tests.

What to put there?
Please, provide some docs!

```
key = os.getenv("DETA_SDK_TEST_PROJECT_KEY")
name = os.getenv("DETA_SDK_TEST_DRIVE_NAME")
host = os.getenv("DETA_SDK_TEST_DRIVE_HOST")
```

**Comment by abdelhai** [comment]
@leits Thanks for pointing this out. We will fix thanks soon :)

**Comment by abdelhai** [comment]
We added a contributing guide. Thanks for the feedback!
