### ISSUE TITLE
What is detalib.app?

### ISSUE THREAD

**Issue by leits** [deta/deta-python#49]
https://github.com/deta/deta-python/blob/5d0e5ef6b2ffa319403e55dfcb46ca5daf7410d0/deta/__init__.py#L10-L15

So what is it? 🤔

**Comment by abdelhai** [comment]
@leits this a simple handler for our cron events: https://docs.deta.sh/docs/micros/cron#code

**Comment by leits** [comment]
But it means that `@app.lib.cron()` doesn't work locally and will crash the app 😓

**Comment by abdelhai** [comment]
Yep. We don't have an elegant way of handling this locally yet.  
It's recommended for now to code/debug cron inside a Micro directly.

**Comment by leits** [comment]
Maybe it's good to add some mocked lib.cron in the client?
If you think it's a good idea, I can make a pull request for this feature.

**Comment by abdelhai** [comment]
@leits I will note this for our next release, maybe we could put `App` back in the SDK. We need to think about it.

**Comment by abdelhai** [comment]
detalib will probably disappear soon

**Comment by eggplants** [comment]
> detalib will probably disappear soon

Any updates on this?

**Comment by lemonyte** [comment]
It will probably be removed in v2, since cron is now handled differently ([docs](https://deta.space/docs/en/build/fundamentals/the-space-runtime/actions#scheduled-actions)).
