### ISSUE TITLE
send_email function in __init__.py

### ISSUE THREAD

**Issue by IsraelWald** [deta/deta-python#57]
I was browsing the source code for Deta and I noticed a send_email function. Is this feature fully implemented yet? And if so, does it work when the code is not running in a micro?

**Comment by aavshr** [comment]
hello, sorry `send_email` will not work currently.

**Comment by IsraelWald** [comment]
Ok thanks for the prompt response. Is there a plan to implement it in the future?

**Comment by aavshr** [comment]
Sorry nothing concretely for emails as of yet, we'll let you know if we plan something.
