### ISSUE TITLE
cron job App is not defined

### ISSUE THREAD

**Issue by rainyear** [deta/deta-python#58]
Cron and HTTP example:

`from deta import App`

ImportError: cannot import name 'App' from 'deta'

**Comment by aavshr** [comment]
hello, the import only works when the code is deployed on a [Deta Micro](https://docs.deta.sh/docs/micros/about).

**Comment by rainyear** [comment]
I got this error from visor:

```
Traceback (most recent call last):
  File "/opt/python/detalib/debugger.py", line 142, in wrap
    result = func(event, context)
  File "/var/task/_entry.py", line 12, in handler
    import main  # noqa
  File "/var/task/main.py", line 8, in <module>
    app = App(FastAPI())
NameError: name 'App' is not defined
```

**Comment by aavshr** [comment]
do you get this error even after `from deta import App`?

**Comment by rainyear** [comment]
My fault. I forgot to deploy.

But I think it's better to return an empty `App` object in the local package, so that we dont need to change the code every time after debug locally.

**Comment by aavshr** [comment]
> But I think it's better to return an empty App object in the local package, so that we dont need to change the code every time after debug locally.

Yes, I agree. Thank you for the feedback. We also need to update the documentation to let people know about this in general.
