### ISSUE TITLE
Link to the docs in README is not working (404)

### ISSUE THREAD

**Issue by senpos** [deta/deta-python#6]
>Supports Python 3.5+ only. [Read the docs.](https://docs.deta.sh/docs/lib)  

Currently `Read the docs.` link in the [README.md](https://github.com/deta/deta-python/blob/master/README.md) sends users to https://docs.deta.sh/docs/lib, which replies with 404.

I believe, it should be either the docs home page (https://docs.deta.sh/docs/home) or SDK page (https://docs.deta.sh/docs/base/sdk).

**Comment by aavshr** [comment]
thank @Senpos , sorry for the late response. 

Issue has been fixed, closing it!
