### ISSUE TITLE
Deta is storing the wrong int

### ISSUE THREAD

**Issue by eeriemyxi** [deta/deta-python#62]
```py
        await inter.response.defer()
        print(channel.id)
        await self.db.put(channel.id, "v_channel")
```
        
it prints, `921301271112187924` but what it stores in the database is, `921301271112187900`

**Comment by aavshr** [comment]
hi @m-y-x-i , this behavior is because of this: https://docs.deta.sh/docs/base/sdk#storing-numbers 

Please, store large ints as strings.
