### ISSUE TITLE
Questions: Does Deta supports npm?

### ISSUE THREAD

**Issue by Legendnic** [deta/deta-python#63]
Hello. I am interested to use Deta as my main server. Thus I would like to know if Deta support npm and add either angular, react or vuejs?

**Comment by aavshr** [comment]
hi @Legendnic , yes we support `node` and you can use `npm` to manage your packages. For more details/questions please use our slack/discord/intercom or send us an email. 

Since this issue is not related to the python SDK, I'm closing this here.
