### ISSUE TITLE
Keyword argument expire_at for base.put() method not found (Python)

### ISSUE THREAD

**Issue by HernandezCU** [deta/deta-python#67]
I am writing to a Deta base and trying to use the expire_at functionality of Deta bases.
Whenever I run the project locally everything works fine, however when I deploy my project to a micro, the following exception is raised:

put() got an unexpected keyword argument 'expire_at'

Python 3.9

**Comment by HernandezCU** [comment]
same issue if I use the 'expire_in' keyword arguement

**Comment by aavshr** [comment]
hi @HernandezCU , this is because Micros are locked with an older version of the SDK. You need to specify `deta` in your `requirements.txt` file and deploy with `deta deploy` to install the latest version.

**Comment by HernandezCU** [comment]
So sorry, must have missed this in the docs, I assumed latest Deta version was running on all micros, 
Thanks, and sorry for the inconvenience
