### ISSUE TITLE
Deta Command Not Found

### ISSUE THREAD

**Issue by tiwarikaran** [deta/deta-python#73]
I am trying to install Deta but the curl commands work and a hidden folder is also created under /Users/ktay. 
But when I run the sole command "deta" my terminal throws a classic error,
"deta" command not found.

Any ideas what I am doing wrong would be of great help

**Comment by abdelhai** [comment]
hi @tiwarikaran try to close you terminal and reopen it. btw wrong project, so will close this thread. feel free to reach out on our discord, thanks!
