### ISSUE TITLE
Micro erroring due to detalib

### ISSUE THREAD

**Issue by x3221** [deta/deta-python#81]
Keep getting this error when trying to run python micros: Runtime.ImportModuleError: Unable to import module '_entry': No module named 'detalib'

I don't include detalib in my requirements.txt but it keeps getting added automatically.

**Comment by Alexqwesa** [comment]
i have the same issue, did someone find a fix yet?

full error log:
```
Error Type:
Runtime.ImportModuleError

Error Message:
Unable to import module '_entry': No module named 'detalib'

Logs:
time="2023-04-12T17:00:59Z" level=info msg="serving logs listener on sandbox.localdomain:1234" agent=logsApiAgent
TELEMETRY	Name: telemetry-extension	State: Subscribed	Types: [Function]
```

**Comment by lemonyte** [comment]
detalib is unrelated to deta-python, and should no longer cause issues after the Python runtime revamp described [here](https://deta.space/changelog/post-13).

**Comment by eggplants** [comment]
> detalib is unrelated to deta-python, and should no longer cause issues after the Python runtime revamp described [here](https://deta.space/changelog/post-13).

Any updates on this?

**Comment by hozan23** [comment]
detaLib has been completely removed from the deta-python sdk, so this error should no longer exist."
