### ISSUE TITLE
The update() method seems to have a problem

### ISSUE THREAD

**Issue by lu-yanpeng** [deta/deta-python#84]
I have data like this

![屏幕截图 2023-06-02 033429](https://github.com/deta/deta-python/assets/54030901/d6f95f31-f47a-4d3b-9614-446610b56cc2)

When I use the `db.update(key='test', updates={'text': ''})` method to update it and specify text as '', I want it to save an empty string, but it will actually save `null`.

![屏幕截图 2023-06-02 034149](https://github.com/deta/deta-python/assets/54030901/35928708-ffbd-4341-9a99-c12fc2cf67ab)

The same situation occurs when updating the object.

![屏幕截图 2023-06-02 034804](https://github.com/deta/deta-python/assets/54030901/23accf00-26aa-413c-b192-ee28d6de770a)

Is this the correct behavior? How do I save an empty string?

**Comment by abdelhai** [comment]
this might be a ui bug. could you check using the sdk if the value is actually an empty string?
